/**
 * Finance Tools registry — 14 calculators.
 * Kept server-safe (no React/lucide imports) so sitemap.ts can consume it.
 * These entries are merged into lib/tools.ts TOOL_CATEGORIES.
 */
import type { Tool, ToolCategory } from "./tools";

export const FINANCE_TOOLS: Tool[] = [
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    href: "/sip-calculator",
    description: "Estimate the future value of your monthly SIP investments",
    tagline: "SIP Calculator",
    stat: "Step-up · Inflation adjusted",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest",
    href: "/compound-interest-calculator",
    description: "See how your principal grows with compound interest",
    tagline: "Compound Interest Calculator",
    stat: "Any frequency · Year-wise table",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    href: "/emi-calculator",
    description: "Monthly EMI, interest & full amortization schedule",
    tagline: "EMI Calculator",
    stat: "Loan · Amortization · Fee",
    badge: "Popular",
    badgeTone: "primary",
  },
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    href: "/gst-calculator",
    description: "Add or remove GST with CGST/SGST split",
    tagline: "GST Calculator",
    stat: "CGST · SGST · IGST slabs",
    badge: "Popular",
    badgeTone: "primary",
  },
  {
    slug: "fd-calculator",
    name: "FD Calculator",
    href: "/fd-calculator",
    description: "Fixed deposit maturity value & interest earned",
    tagline: "FD Calculator",
    stat: "Quarterly compounding · Growth chart",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "cagr-calculator",
    name: "CAGR Calculator",
    href: "/cagr-calculator",
    description: "Annualized growth rate of your investment",
    tagline: "CAGR Calculator",
    stat: "Total return · Growth curve",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    href: "/roi-calculator",
    description: "Return on investment & annualized ROI",
    tagline: "ROI Calculator",
    stat: "Profit · ROI % · Annualized",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "income-tax-calculator",
    name: "Income Tax",
    href: "/income-tax-calculator",
    description: "Estimate Indian income tax — old & new regimes",
    tagline: "Income Tax Calculator",
    stat: "Old/New regime · Cess · Effective rate",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "retirement-calculator",
    name: "Retirement Calculator",
    href: "/retirement-calculator",
    description: "Project your retirement corpus & monthly income",
    tagline: "Retirement Calculator",
    stat: "Corpus · 4% rule · Inflation",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    href: "/discount-calculator",
    description: "Final price and savings after a discount",
    tagline: "Discount Calculator",
    stat: "Save ₹ · Final price · % off",
    badge: "Free",
    badgeTone: "success",
  },
  {
    slug: "profit-margin-calculator",
    name: "Profit Margin",
    href: "/profit-margin-calculator",
    description: "Profit, margin & markup from cost and price",
    tagline: "Profit Margin Calculator",
    stat: "Margin · Markup · Profit ₹",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "stock-average-calculator",
    name: "Stock Average",
    href: "/stock-average-calculator",
    description: "Average buy price across multiple purchases",
    tagline: "Stock Average Calculator",
    stat: "Unlimited entries · P&L estimate",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "salary-calculator",
    name: "Salary Calculator",
    href: "/salary-calculator",
    description: "Estimate take-home salary from CTC",
    tagline: "Salary Calculator",
    stat: "PF · Tax · Net monthly/yearly",
    badge: "New",
    badgeTone: "primary",
  },
  {
    slug: "inflation-calculator",
    name: "Inflation Calculator",
    href: "/inflation-calculator",
    description: "How inflation erodes purchasing power",
    tagline: "Inflation Calculator",
    stat: "Future value · Power lost",
    badge: "New",
    badgeTone: "primary",
  },
];

export const FINANCE_CATEGORY: ToolCategory = {
  id: "finance",
  label: "Finance Tools",
  tools: FINANCE_TOOLS,
};
