import type { ToolSeoContent } from "./seo-content";

/**
 * Unique SEO content for every Developer Tool. Keyed by the same slug used in
 * lib/tools.ts, so ToolSeoContent can resolve them exactly like image tools.
 */
export const DEV_TOOL_SEO_CONTENT: Record<string, ToolSeoContent> = {
  "json-formatter": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["Beautify & minify", "Collapsible tree view", "Error line numbers", "100% browser-based"],
    intro: {
      heading: "JSON Formatter — Beautify, Minify & Validate JSON Online",
      paragraphs: [
        "The JSON Formatter cleans up messy JSON in seconds: paste or upload any JSON blob, hit Beautify for a perfectly indented, human-readable structure, or Minify to strip every unnecessary space. A collapsible tree view lets you explore nested data without reading braces.",
        "Invalid JSON is never left to guesswork — the tool highlights the exact line and column of the error with a plain-English explanation. Everything runs locally in your browser, so even sensitive configuration or API payloads never leave your device.",
      ],
    },
    benefits: [
      { title: "Instant Beautify", description: "One click turns minified JSON into clean, 2-space indented output that is easy to read and diff." },
      { title: "Collapsible Tree View", description: "Explore deeply nested objects and arrays with expand/collapse — no manual brace matching." },
      { title: "Precise Error Reporting", description: "See the exact line, column, and a human-readable reason when your JSON is invalid." },
      { title: "100% Private", description: "All parsing happens in your browser. Paste sensitive configs and API payloads with confidence." },
    ],
    features: [
      { title: "Beautify", description: "Format JSON with 2-space indentation for readable output." },
      { title: "Minify", description: "Strip whitespace to shrink JSON for storage or transmission." },
      { title: "Tree View", description: "Interactive collapsible view of the parsed structure with copyable values." },
      { title: "Upload & Download", description: "Load a .json file from disk and download the result with one click." },
      { title: "Copy Anywhere", description: "Copy the formatted, minified, or a single tree node's value to the clipboard." },
    ],
    howTo: {
      heading: "How to Format JSON",
      description: "Make any JSON readable in three quick steps.",
      steps: [
        { name: "Paste or upload JSON", text: "Type, paste, or load a .json file with invalid or minified content." },
        { name: "Choose an action", text: "Click Beautify, Minify, or switch to the tree view for a visual structure." },
        { name: "Copy or download", text: "Copy the output to your clipboard or download it as a .json file." },
      ],
    },
    faqs: [
      { question: "What is a JSON formatter?", answer: "A JSON formatter takes raw or minified JSON and reformats it with proper indentation, making it readable. This tool also minifies JSON and validates it." },
      { question: "Is the JSON formatter free?", answer: "Yes, it is completely free with no sign-ups, limits, or watermarks." },
      { question: "Does it work on my private or sensitive data?", answer: "Yes — all parsing happens locally in your browser. Your JSON never leaves your device." },
      { question: "What does Beautify do?", answer: "Beautify parses your JSON and re-prints it with 2-space indentation so nested objects and arrays are easy to read." },
      { question: "What does Minify do?", answer: "Minify removes all unnecessary whitespace, producing the smallest valid JSON string — useful for storage or API payloads." },
      { question: "How does the tree view work?", answer: "The tree view renders your parsed JSON as collapsible nodes. Click arrows to expand objects and arrays, and click a value to copy it." },
      { question: "What happens if my JSON is invalid?", answer: "The tool shows the exact line and column of the error with a plain-English explanation, so you can fix it immediately." },
      { question: "Can I format a file?", answer: "Yes, upload any .json file and the tool reads it into the editor automatically. You can also download the result as a .json file." },
      { question: "Does it support large JSON?", answer: "It handles large payloads comfortably in modern browsers, though extremely large files (tens of MB) can be slower." },
      { question: "Does it work on mobile?", answer: "Yes, the tool is fully responsive and works on desktop, tablet, and mobile browsers." },
      { question: "Can I copy just one value from the tree?", answer: "Yes — in the tree view, clicking a scalar value copies it to your clipboard without copying the whole document." },
      { question: "Why should I minify JSON?", answer: "Minified JSON is smaller, which reduces bandwidth, storage costs, and payload transfer time in APIs and databases." },
    ],
  },

  "json-validator": {
    meta: { readTime: "3 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["Real-time validation", "Error line numbers", "Plain-English errors", "Pretty print"],
    intro: {
      heading: "JSON Validator — Check Your JSON in Real Time",
      paragraphs: [
        "The JSON Validator checks your JSON as you type, with instant green/red feedback, the exact line and column of any problem, and a plain-English explanation of what went wrong. No more hunting through braces by eye.",
        "Valid JSON can be pretty-printed with one click, and everything runs locally in your browser — so test API responses, config files, and webhook payloads in complete privacy.",
      ],
    },
    benefits: [
      { title: "Validate as You Type", description: "Real-time feedback shows instantly whether your JSON is valid." },
      { title: "Pinpoint Errors", description: "Get the exact line and column plus a human-readable reason for every problem." },
      { title: "One-Click Pretty Print", description: "Turn valid JSON into clean, indented output in a single click." },
      { title: "Private by Default", description: "Nothing is uploaded — validation runs entirely on your device." },
    ],
    features: [
      { title: "Real-Time Checking", description: "Every keystroke re-validates instantly with a clear pass/fail indicator." },
      { title: "Error Line & Column", description: "Precise position reporting with the offending snippet highlighted." },
      { title: "Plain-English Explanations", description: "Understandable messages like 'Missing closing brace' instead of cryptic codes." },
      { title: "Pretty Print", description: "Format valid JSON into readable, 2-space indented output." },
      { title: "Copy Results", description: "Copy the formatted JSON or the error report to the clipboard." },
    ],
    howTo: {
      heading: "How to Validate JSON",
      description: "Check and fix your JSON in three simple steps.",
      steps: [
        { name: "Paste your JSON", text: "Paste or type JSON into the editor — validation starts immediately." },
        { name: "Read the feedback", text: "A green badge confirms it's valid; a red badge shows the line, column, and explanation." },
        { name: "Fix or format", text: "Correct the reported issue, or pretty-print valid JSON for a cleaner copy." },
      ],
    },
    faqs: [
      { question: "What is a JSON validator?", answer: "A JSON validator checks whether a string is syntactically valid JSON and reports exactly where problems occur, with human-readable explanations." },
      { question: "Is validation instant?", answer: "Yes, the tool validates on every keystroke in real time — no submit button needed." },
      { question: "Is the JSON validator free?", answer: "Yes, completely free with no sign-ups or limits." },
      { question: "Are my JSON payloads uploaded?", answer: "No. Validation runs entirely in your browser; your data never leaves your device." },
      { question: "What does the line number mean?", answer: "It's the 1-based line in your input where the parser found a problem, so you can jump straight to the error." },
      { question: "Why does it say 'Unexpected token'?", answer: "That means a character appeared where the JSON grammar didn't expect it — commonly a stray comma, quote, or brace." },
      { question: "Can it validate a JSON file?", answer: "Yes — upload a .json file and it's validated immediately. You can also download the pretty-printed result." },
      { question: "Does pretty print change my data?", answer: "No, it only adds whitespace. The parsed data is identical; pretty print just makes it readable." },
      { question: "Can trailing commas be validated?", answer: "Trailing commas are invalid in standard JSON, so they are reported as errors — which is correct behavior." },
      { question: "Does it work on mobile?", answer: "Yes, the tool is fully responsive and works on any device." },
      { question: "Can I copy the error report?", answer: "Yes, the error message and position can be copied for sharing or debugging." },
      { question: "What's the difference between this and the JSON formatter?", answer: "The validator focuses on checking correctness with real-time feedback, while the formatter adds beautify, minify, and a tree view." },
    ],
  },

  "base64-encoder": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["Text, file & image input", "UTF-8 safe", "Copy & download", "100% browser-based"],
    intro: {
      heading: "Base64 Encoder — Encode Text, Files & Images to Base64",
      paragraphs: [
        "The Base64 Encoder converts any text, file, or image into a Base64 string right in your browser. Perfect for embedding images into HTML, CSS, or emails, passing binary data through JSON APIs, or preparing data for applications that only accept ASCII.",
        "Unlike many online tools, it handles UTF-8 text correctly (emoji and non-Latin scripts included) and can encode full files into data URLs with a single click. Everything runs locally, so your files are never uploaded.",
      ],
    },
    benefits: [
      { title: "Text, File & Image Modes", description: "Encode plain text, whole files, or images — including data URL output." },
      { title: "Correct UTF-8 Handling", description: "Emoji, Arabic, Chinese, and other non-Latin1 text encode without corruption." },
      { title: "Data URL Ready", description: "Get ready-to-paste data URLs for HTML img tags, CSS, and emails." },
      { title: "Private & Free", description: "Encoding runs in your browser — files never leave your device." },
    ],
    features: [
      { title: "Text Encoding", description: "Encode any string, with a live character and byte counter." },
      { title: "File Encoding", description: "Select any file and get its Base64 representation instantly." },
      { title: "Image Data URL", description: "Encode an image and copy the full data:image/... URL for inline use." },
      { title: "Copy & Download", description: "Copy the result or download it as a .txt file." },
      { title: "Decode Built In", description: "A toggle switches to decoding so one page handles both directions." },
    ],
    howTo: {
      heading: "How to Encode to Base64",
      description: "Encode text or a file in three steps.",
      steps: [
        { name: "Pick an input mode", text: "Choose Text, File, or Image depending on what you want to encode." },
        { name: "Enter or select your data", text: "Type your text, pick a file, or choose an image from your device." },
        { name: "Copy or download", text: "Copy the Base64 string or data URL, or download it as a file." },
      ],
    },
    faqs: [
      { question: "What is Base64?", answer: "Base64 is an encoding that represents binary data as ASCII text using 64 characters. It's widely used to embed files in HTML, CSS, JSON, and emails." },
      { question: "Is the Base64 encoder free?", answer: "Yes, completely free with no sign-ups or usage limits." },
      { question: "Are my files uploaded?", answer: "No — encoding happens entirely in your browser, so your data never leaves your device." },
      { question: "Does it support emoji and non-English text?", answer: "Yes. The tool encodes UTF-8 correctly, so emoji and scripts like Arabic, Chinese, and Hindi work perfectly." },
      { question: "What is a data URL?", answer: "A data URL embeds the file content directly in the URL (data:image/png;base64,...). It's used to inline images in HTML, CSS, and email." },
      { question: "Can I encode an image to paste into HTML?", answer: "Yes — use Image mode, then copy the data URL and put it in an <img src=\"...\"> tag." },
      { question: "Can I download the encoded output?", answer: "Yes, the result downloads as a .txt file with one click." },
      { question: "What's the difference between Base64 and URL-safe Base64?", answer: "URL-safe Base64 replaces + and / with - and _ so the output can appear in URLs without encoding. This tool outputs standard Base64." },
      { question: "Does encoding increase file size?", answer: "Yes, Base64 inflates data by roughly 33%. The encoded string is a text representation, not a compression format." },
      { question: "Can I encode a file larger than my browser memory?", answer: "Extremely large files may be slow, but typical files (up to tens of MB) encode quickly in modern browsers." },
      { question: "Does it work on mobile?", answer: "Yes, the tool works on desktop, tablet, and mobile browsers." },
      { question: "Why is my encoded text different from other tools?", answer: "Differences usually come from UTF-8 handling. This tool is UTF-8 correct, matching standards like TextEncoder." },
    ],
  },

  "base64-decoder": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["Decode text & data URLs", "UTF-8 safe", "Image preview", "Copy & download"],
    intro: {
      heading: "Base64 Decoder — Decode Text, Files & Images Instantly",
      paragraphs: [
        "The Base64 Decoder converts Base64 strings back into readable text or binary files right in your browser. Paste any Base64 string or data URL and get the original content instantly — perfect for inspecting API payloads, JWT segments, and embedded images.",
        "It detects image data URLs automatically and renders a live preview so you can verify exactly what you're decoding. UTF-8 text like emoji and non-Latin scripts decodes correctly, and everything runs locally for complete privacy.",
      ],
    },
    benefits: [
      { title: "Text & Binary Decoding", description: "Decode Base64 strings back to readable text or binary files." },
      { title: "Automatic Image Preview", description: "Image data URLs render as a live preview — no guessing." },
      { title: "UTF-8 Correct", description: "Emoji and non-Latin text decode correctly, unlike naive atob() tools." },
      { title: "100% Private", description: "Decoding happens in your browser; nothing is uploaded." },
    ],
    features: [
      { title: "Text Decoding", description: "Decode any Base64 string back to its original UTF-8 text." },
      { title: "Data URL Support", description: "Paste a full data:...;base64,... URL and it's decoded automatically." },
      { title: "Image Preview", description: "Decoded images appear in a live preview panel." },
      { title: "File Download", description: "Save decoded binary data back to a file with one click." },
      { title: "Error Feedback", description: "Invalid Base64 input is flagged with a clear message." },
    ],
    howTo: {
      heading: "How to Decode Base64",
      description: "Decode any Base64 string in three steps.",
      steps: [
        { name: "Paste your Base64", text: "Paste a Base64 string or data URL into the input box." },
        { name: "Watch it decode", text: "The decoded text, file, or image preview appears instantly." },
        { name: "Copy or download", text: "Copy the decoded text or download the original file." },
      ],
    },
    faqs: [
      { question: "What is a Base64 decoder?", answer: "It converts Base64-encoded text back into its original content — readable text, binary files, or images." },
      { question: "Is the Base64 decoder free?", answer: "Yes, completely free with no sign-ups or limits." },
      { question: "Are my strings uploaded?", answer: "No, decoding runs entirely in your browser." },
      { question: "Can it decode a data URL?", answer: "Yes — paste a full data:image/png;base64,... URL and the tool extracts and decodes the payload automatically." },
      { question: "Will images show a preview?", answer: "Yes, image data URLs render in a preview panel so you can verify the result before downloading." },
      { question: "Does it handle emoji correctly?", answer: "Yes, decoded UTF-8 text (emoji and non-Latin scripts) is handled correctly." },
      { question: "What if my Base64 is invalid?", answer: "The tool shows a clear error message so you can fix the input." },
      { question: "Can I decode to a file?", answer: "Yes — if the decoded content is binary, you can download it as a file." },
      { question: "What's a JWT? Can I decode one here?", answer: "JWTs use URL-safe Base64 for their three segments. For a full breakdown with expiry, use our dedicated JWT Decoder tool." },
      { question: "Does it work on mobile?", answer: "Yes, the tool is fully responsive." },
      { question: "Why does my decoded text show garbled characters?", answer: "That usually means the input isn't valid Base64 or was encoded from binary, not text. Try the file download to recover binary content." },
      { question: "Is Base64 decodable by anyone?", answer: "Yes — Base64 is an encoding, not encryption. Never put secrets in Base64 expecting privacy." },
    ],
  },

  "password-generator": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["Entropy calculation", "Strength meter", "Exclude similar chars", "Cryptographic randomness"],
    intro: {
      heading: "Password Generator — Strong, Random Passwords with Entropy",
      paragraphs: [
        "The Password Generator creates cryptographically strong random passwords in your browser. Choose the length and character sets — uppercase, lowercase, numbers, and symbols — and a live strength meter plus entropy readout tell you exactly how secure each password is.",
        "Options like excluding similar characters (1, l, I, 0, O) make passwords easier to type on any keyboard, and because generation uses the browser's crypto API, no password ever leaves your device.",
      ],
    },
    benefits: [
      { title: "Crypto-Grade Randomness", description: "Uses the browser's cryptographic random generator — not Math.random()." },
      { title: "Live Strength Meter", description: "See weak-to-strong feedback with a color-coded meter as options change." },
      { title: "Entropy Readout", description: "Bits of entropy quantify exactly how resistant the password is to brute force." },
      { title: "100% Private", description: "Passwords are generated on your device and never transmitted anywhere." },
    ],
    features: [
      { title: "Length Control", description: "Adjust password length from 4 to 64 characters with a slider." },
      { title: "Character Sets", description: "Toggle uppercase, lowercase, numbers, and symbols independently." },
      { title: "Exclude Similar", description: "Remove easily confused characters like 1/l/I and 0/O." },
      { title: "Strength Meter", description: "Color-coded weak/fair/good/strong feedback based on character pool and length." },
      { title: "Entropy Display", description: "Shows bits of entropy so you can compare password strength objectively." },
      { title: "One-Click Copy", description: "Copy the generated password with a single click." },
    ],
    howTo: {
      heading: "How to Generate a Strong Password",
      description: "Create a secure password in three steps.",
      steps: [
        { name: "Set the options", text: "Choose the length and toggle the character sets you want included." },
        { name: "Check the strength", text: "Review the strength meter and entropy — aim for at least 60–80 bits." },
        { name: "Copy & use it", text: "Copy the password and use it in your accounts. Consider a password manager." },
      ],
    },
    faqs: [
      { question: "How does the password generator work?", answer: "It uses the browser's cryptographically secure random number generator to pick characters from the enabled sets — no pattern, no predictability." },
      { question: "Is it free?", answer: "Yes, completely free with no sign-ups or limits." },
      { question: "Are generated passwords sent anywhere?", answer: "No. Generation happens locally on your device; passwords are never transmitted." },
      { question: "What is entropy?", answer: "Entropy measures unpredictability in bits. Each bit doubles the guesses needed, so 80+ bits is generally considered strong." },
      { question: "How strong should my password be?", answer: "Aim for at least 12–16 characters across multiple character sets, which this tool typically rates 80+ bits." },
      { question: "Should I use symbols?", answer: "Symbols expand the character pool and raise entropy, but length matters more. Many password managers recommend passphrases instead." },
      { question: "What does 'exclude similar characters' do?", answer: "It removes characters like 1, l, I, 0, and O that are easy to confuse, making the password easier to type." },
      { question: "Can I choose the length?", answer: "Yes, from 4 to 64 characters via a slider." },
      { question: "Is this password safe to reuse?", answer: "Never reuse passwords across sites. Generate a unique password for every account and use a password manager." },
      { question: "Does it work offline?", answer: "Yes — once the page is loaded, generation works entirely offline in your browser." },
      { question: "Does it work on mobile?", answer: "Yes, the tool is fully responsive." },
      { question: "Why is my short password rated weak?", answer: "Short passwords with few character sets have low entropy, so they're rated weak — lengthen it or add character sets." },
    ],
  },

  "uuid-generator": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["UUID v1 · v4 · v7", "Bulk generation", "Copy all", "Download as file"],
    intro: {
      heading: "UUID Generator — v1, v4 & v7 with Bulk Generation",
      paragraphs: [
        "The UUID Generator produces universally unique identifiers in the three most-used versions: UUID v1 (time-based), UUID v4 (fully random), and UUID v7 (time-ordered random). Generate one or thousands at once, copy them all with a single click, or download them as a file.",
        "Time-ordered UUID v7 values sort chronologically, which is great for database keys and indexes. Everything is generated locally using your browser's crypto API — no network calls, no tracking.",
      ],
    },
    benefits: [
      { title: "v1, v4 & v7 Support", description: "The three most common UUID versions, each with a clear explanation of when to use it." },
      { title: "Bulk Generation", description: "Generate up to 10,000 UUIDs at once for seed data and test fixtures." },
      { title: "Copy All & Download", description: "Copy every UUID to the clipboard or download as .txt, .csv, or .json." },
      { title: "Crypto-Secure", description: "Uses the browser's cryptographic randomness — never Math.random()." },
    ],
    features: [
      { title: "UUID v4", description: "Fully random UUIDs — the default choice for most applications." },
      { title: "UUID v1", description: "Time-based UUIDs including timestamp, clock sequence, and node components." },
      { title: "UUID v7", description: "Time-ordered random UUIDs that sort chronologically — ideal for database keys." },
      { title: "Bulk Mode", description: "Set a count up to 10,000 and generate them all instantly." },
      { title: "Multiple Download Formats", description: "Export as .txt, .csv, or .json for use in seed scripts and tests." },
      { title: "Uppercase & Hyphens", description: "Optional uppercase output and hyphen removal via simple options." },
    ],
    howTo: {
      heading: "How to Generate UUIDs",
      description: "Generate one or many UUIDs in three steps.",
      steps: [
        { name: "Pick a version", text: "Choose v1 (time-based), v4 (random), or v7 (time-ordered)." },
        { name: "Set the count", text: "Generate a single UUID or enter a bulk count up to 10,000." },
        { name: "Copy or download", text: "Copy them all to the clipboard or download as txt, csv, or json." },
      ],
    },
    faqs: [
      { question: "What is a UUID?", answer: "A UUID (Universally Unique Identifier) is a 128-bit identifier formatted as 36 characters, designed to be unique across all systems without coordination." },
      { question: "Is the UUID generator free?", answer: "Yes, completely free with no sign-ups or limits." },
      { question: "What's the difference between UUID v4 and v7?", answer: "v4 is fully random. v7 encodes a timestamp plus randomness, so v7 values sort chronologically — useful for database keys and pagination." },
      { question: "When should I use UUID v1?", answer: "v1 is time-based with node information. It's rarely recommended today because it can leak timing and machine details; prefer v4 or v7." },
      { question: "Can I generate multiple UUIDs at once?", answer: "Yes, up to 10,000 at a time in bulk mode." },
      { question: "Can I download the UUIDs?", answer: "Yes — export as .txt, .csv, or .json files." },
      { question: "Are the UUIDs truly random?", answer: "v4 and v7 use the browser's cryptographically secure random API, so they're unpredictable." },
      { question: "Why do UUIDs sort weirdly in my database?", answer: "Random UUIDs (v4) have no ordering. Switch to v7 for chronological sort order." },
      { question: "Can I remove the hyphens?", answer: "Yes, an option strips hyphens for the 32-character compact form." },
      { question: "Does it work offline?", answer: "Yes — generation happens entirely in your browser." },
      { question: "Does it work on mobile?", answer: "Yes, the tool is fully responsive." },
      { question: "Can I use UUIDs as primary keys?", answer: "Yes, but index them properly. Time-ordered v7 UUIDs typically perform better than random v4 in B-tree indexes." },
    ],
  },

  "qr-code-generator": {
    meta: { readTime: "5 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["URL · WiFi · Email · UPI", "Custom colors & logo", "PNG · SVG · PDF export", "100% browser-based"],
    intro: {
      heading: "QR Code Generator — URL, WiFi, WhatsApp & More",
      paragraphs: [
        "The QR Code Generator creates scannable QR codes for URLs, plain text, WiFi networks, emails, phone numbers, SMS, WhatsApp, and UPI payments — all in your browser. Customize colors, add your logo, and download as PNG, SVG, or PDF.",
        "A live preview updates as you type, so you always know the QR is scannable before you export. Nothing is uploaded: generation runs entirely on your device, making it safe for internal links and sensitive content.",
      ],
    },
    benefits: [
      { title: "8 QR Content Types", description: "URL, text, WiFi, email, phone, SMS, WhatsApp, and UPI in one tool." },
      { title: "Brand It With a Logo", description: "Overlay your logo in the center to make QR codes on-brand." },
      { title: "PNG, SVG & PDF Export", description: "Raster or vector output for print, web, and packaging." },
      { title: "Private & Free", description: "Codes are generated locally in your browser — never uploaded." },
    ],
    features: [
      { title: "WiFi QR Codes", description: "Encode network name, password, and security type for instant join." },
      { title: "WhatsApp & SMS", description: "Pre-fill a chat or message with a single scan." },
      { title: "UPI Payments", description: "Generate payment QR codes with amount, note, and payee details." },
      { title: "Custom Colors", description: "Pick foreground and background colors that match your brand." },
      { title: "Logo Overlay", description: "Upload an image and center it in the QR code." },
      { title: "Multiple Export Formats", description: "Download as PNG, SVG, or PDF at any size." },
    ],
    howTo: {
      heading: "How to Create a QR Code",
      description: "Generate and download a QR code in three steps.",
      steps: [
        { name: "Choose a type", text: "Pick URL, text, WiFi, email, phone, SMS, WhatsApp, or UPI." },
        { name: "Fill in the details", text: "Enter the link or content, then customize colors and add a logo if you want." },
        { name: "Download", text: "Preview the live code, then export as PNG, SVG, or PDF." },
      ],
    },
    faqs: [
      { question: "How do I make a QR code?", answer: "Choose a content type, enter the details (URL, WiFi credentials, etc.), and download the generated code as PNG, SVG, or PDF." },
      { question: "Is the QR code generator free?", answer: "Yes, completely free with no sign-ups or watermarks." },
      { question: "Are the QR codes created on my device?", answer: "Yes — all generation happens locally in your browser. Nothing is uploaded." },
      { question: "Can I make a WiFi QR code?", answer: "Yes — enter the network name, password, and security type (WPA/WEP/Open) to create a scan-to-join code." },
      { question: "Can I add my logo to the QR code?", answer: "Yes, upload an image and it's overlaid in the center. Keep the logo under ~25% of the code's width to stay scannable." },
      { question: "What formats can I download?", answer: "PNG (raster), SVG (vector, scales infinitely), and PDF (print-ready)." },
      { question: "Can I change the colors?", answer: "Yes, set custom foreground and background colors. Keep the contrast high for reliable scanning." },
      { question: "Can I make a UPI payment QR code?", answer: "Yes — enter your UPI ID, optional payee name, amount, and note to create a payment code." },
      { question: "How does the WhatsApp QR work?", answer: "It encodes a wa.me link so scanning opens a chat with your number pre-filled." },
      { question: "Will my QR code expire?", answer: "No — the code is a static image of your content. It works forever unless you regenerate it with different data." },
      { question: "Can I make a QR code for an email?", answer: "Yes, enter the recipient address, subject, and body to create a mailto QR code." },
      { question: "Does it work on mobile?", answer: "Yes, the tool is fully responsive." },
    ],
  },

  "css-gradient-generator": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["Linear · Radial · Conic", "Multi-color stops", "Angle & shape control", "Copy CSS in one click"],
    intro: {
      heading: "CSS Gradient Generator — Linear, Radial & Conic",
      paragraphs: [
        "The CSS Gradient Generator lets you design beautiful CSS gradients visually and copy production-ready code. Choose linear, radial, or conic gradients, add as many color stops as you like, and adjust the angle or shape with live previews.",
        "Every change updates the preview instantly and generates the exact CSS declaration — background, background-image, and full syntax variants — so you can paste straight into your stylesheets.",
      ],
    },
    benefits: [
      { title: "Three Gradient Types", description: "Linear, radial, and conic gradients in one tool." },
      { title: "Unlimited Color Stops", description: "Add, reorder, and fine-tune as many colors as your design needs." },
      { title: "Angle & Shape Control", description: "Slide the angle for linear, or choose shape and position for radial." },
      { title: "Instant CSS Output", description: "Copy the exact CSS declaration with one click." },
    ],
    features: [
      { title: "Linear Gradients", description: "Directional gradients with a 0–360° angle slider." },
      { title: "Radial Gradients", description: "Circle or ellipse gradients with center position control." },
      { title: "Conic Gradients", description: "Rotating color wheels with starting angle and center options." },
      { title: "Color Stops", description: "Add unlimited stops, edit colors, and adjust each stop's position." },
      { title: "Live Preview", description: "A large preview panel updates with every change." },
      { title: "Copy-Ready CSS", description: "Copy the background declaration with modern syntax." },
    ],
    howTo: {
      heading: "How to Create a CSS Gradient",
      description: "Design and copy a gradient in three steps.",
      steps: [
        { name: "Choose the type", text: "Pick linear, radial, or conic and set the angle or shape." },
        { name: "Add color stops", text: "Click to add colors, then adjust each stop's position on the slider." },
        { name: "Copy the CSS", text: "Copy the generated CSS declaration and paste it into your stylesheet." },
      ],
    },
    faqs: [
      { question: "What is a CSS gradient?", answer: "A CSS gradient is a background that transitions smoothly between colors, created with the background-image or background property." },
      { question: "Is the gradient generator free?", answer: "Yes, completely free with no sign-ups." },
      { question: "What gradient types are supported?", answer: "Linear, radial, and conic gradients." },
      { question: "How do I add more colors?", answer: "Use the Add Color button to append stops; each stop has its own color picker and position slider." },
      { question: "What does the angle control do?", answer: "It rotates the direction of a linear gradient from 0° (to top) through 360°." },
      { question: "What is a conic gradient?", answer: "A conic gradient rotates colors around a center point, like a color wheel — great for pie charts and loading spinners." },
      { question: "Can I use the gradient as a background-image?", answer: "Yes, the tool outputs both the shorthand and the background-image form." },
      { question: "Does it work with dark mode?", answer: "Yes, the preview and UI adapt to the site's light and dark themes." },
      { question: "Can I copy the CSS?", answer: "Yes, one click copies the complete CSS declaration." },
      { question: "Does it work on mobile?", answer: "Yes, fully responsive." },
      { question: "Can I add transparency to colors?", answer: "Yes, the color picker includes an alpha channel for semi-transparent stops." },
      { question: "What's the best browser support?", answer: "All three gradient types are supported by every modern browser, including Safari, Chrome, Firefox, and Edge." },
    ],
  },

  "css-box-shadow-generator": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["X · Y · Blur · Spread", "Opacity & inset", "Live preview", "Copy CSS in one click"],
    intro: {
      heading: "CSS Box Shadow Generator — Design Shadows Visually",
      paragraphs: [
        "The CSS Box Shadow Generator helps you create the perfect box shadow with live previews. Adjust X and Y offsets, blur, spread, opacity, and color with sliders, toggle inset shadows for depth, and copy the exact CSS in one click.",
        "Whether you're building soft elevation for cards or sharp inset edges for input fields, the live preview shows your shadow on both light and dark surfaces so it looks right everywhere.",
      ],
    },
    benefits: [
      { title: "Every Property Covered", description: "X, Y, blur, spread, color, opacity, and inset — all controllable." },
      { title: "Live Preview", description: "See your shadow update in real time on light and dark surfaces." },
      { title: "Inset Support", description: "Create inner shadows for depth on buttons and inputs." },
      { title: "Copy-Ready CSS", description: "One click copies the exact box-shadow declaration." },
    ],
    features: [
      { title: "Offset Sliders", description: "Fine-tune X and Y offsets in pixels, including negative values." },
      { title: "Blur & Spread", description: "Control softness and size independently." },
      { title: "Opacity & Color", description: "Set the shadow color with an opacity slider for soft, natural depth." },
      { title: "Inset Toggle", description: "Switch between outer and inner shadows." },
      { title: "Dual-Surface Preview", description: "Preview the shadow on light and dark cards simultaneously." },
      { title: "Instant Copy", description: "Copy the generated CSS to your clipboard." },
    ],
    howTo: {
      heading: "How to Create a Box Shadow",
      description: "Design a shadow and copy the CSS in three steps.",
      steps: [
        { name: "Adjust the sliders", text: "Set X, Y, blur, spread, opacity, and pick a color." },
        { name: "Preview & refine", text: "Check the live preview on light and dark surfaces; toggle inset for inner shadows." },
        { name: "Copy the CSS", text: "Copy the generated box-shadow declaration into your stylesheet." },
      ],
    },
    faqs: [
      { question: "What is a CSS box shadow?", answer: "It's a CSS property that draws a shadow around an element's box, defined by offsets, blur, spread, color, and optional inset." },
      { question: "Is the box shadow generator free?", answer: "Yes, completely free with no sign-ups." },
      { question: "What does blur do?", answer: "Blur controls how soft the shadow edge is — a larger blur creates a softer, more diffuse shadow." },
      { question: "What does spread do?", answer: "Spread grows (positive) or shrinks (negative) the shadow size around the element." },
      { question: "What is an inset shadow?", answer: "An inset shadow is drawn inside the element, creating a recessed effect — ideal for inputs and pressed buttons." },
      { question: "How do I make a soft material shadow?", answer: "Use a small offset (0–4px), a large blur (10–24px), and low opacity (10–25%) with a dark color." },
      { question: "Can I use negative offsets?", answer: "Yes, negative X/Y offsets move the shadow up or left." },
      { question: "Can I copy the CSS?", answer: "Yes, one click copies the full box-shadow declaration." },
      { question: "Does it work in dark mode?", answer: "Yes — the previews adapt to the site theme, and you can see shadows on dark surfaces." },
      { question: "Does it work on mobile?", answer: "Yes, fully responsive." },
      { question: "Can I use this for multiple shadows?", answer: "For multiple layered shadows, generate each separately and combine them with commas." },
      { question: "What browsers support box-shadow?", answer: "All modern browsers support box-shadow, including Safari, Chrome, Firefox, and Edge." },
    ],
  },

  "jwt-decoder": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["Header & payload decode", "Expiry & timestamps", "Human-readable times", "100% browser-based"],
    intro: {
      heading: "JWT Decoder — Decode Header, Payload & Expiry",
      paragraphs: [
        "The JWT Decoder breaks a JSON Web Token into its three parts — header, payload, and signature — with everything decoded and pretty-printed for you. It also surfaces the registered claims like exp, iat, and nbf as human-readable timestamps, so you can see exactly when a token expires.",
        "Great for debugging auth flows, verifying token contents during development, or checking whether a token is still valid. Decoding happens entirely in your browser — tokens are never sent anywhere.",
      ],
    },
    benefits: [
      { title: "Full Token Breakdown", description: "Header, payload, and signature separated and labeled clearly." },
      { title: "Human-Readable Claims", description: "exp, iat, nbf, and more shown as readable local dates, not epoch numbers." },
      { title: "Expiry Awareness", description: "Instantly see if the token is expired, and when it will expire." },
      { title: "100% Private", description: "Decoding runs in your browser — tokens never leave your device." },
    ],
    features: [
      { title: "Three-Part Decoding", description: "Header, payload, and signature displayed in separate panels." },
      { title: "Pretty-Printed JSON", description: "Both JSON parts are formatted for easy reading." },
      { title: "Claim Timestamps", description: "exp, iat, and nbf rendered as human-readable dates." },
      { title: "Expiry Status", description: "A badge shows whether the token is valid, expired, or not yet valid." },
      { title: "Copy Segments", description: "Copy the raw token or any decoded segment with one click." },
      { title: "Signature Info", description: "Shows the signature length so you can verify it was signed." },
    ],
    howTo: {
      heading: "How to Decode a JWT",
      description: "Decode any JWT in three steps.",
      steps: [
        { name: "Paste the token", text: "Paste your JWT (the full three-part token) into the input." },
        { name: "Read the breakdown", text: "Header and payload appear decoded; exp, iat, and nbf show as readable dates." },
        { name: "Check expiry & copy", text: "See the expiry status, then copy any segment you need." },
      ],
    },
    faqs: [
      { question: "What is a JWT?", answer: "A JWT (JSON Web Token) is a compact token with three Base64URL-encoded parts: header, payload, and signature, used for authentication and authorization." },
      { question: "Is the JWT decoder free?", answer: "Yes, completely free with no sign-ups." },
      { question: "Are tokens sent anywhere?", answer: "No — decoding happens entirely in your browser." },
      { question: "Does it verify the signature?", answer: "No, this tool decodes and displays the contents. Signature verification requires the secret key and is done on the server." },
      { question: "What is the exp claim?", answer: "exp is the expiration time of the token, shown here as a human-readable date plus a valid/expired badge." },
      { question: "What are iat and nbf?", answer: "iat is the issued-at time and nbf is the not-before time — both are rendered as readable dates." },
      { question: "Can I copy the decoded payload?", answer: "Yes, copy the pretty-printed payload or the raw token with one click." },
      { question: "Why is my token showing as expired?", answer: "The exp claim is in the past. If you believe it should be valid, check your token generation time and clock." },
      { question: "Does it work with any JWT algorithm?", answer: "Yes, it decodes the header regardless of algorithm (HS256, RS256, ES256, etc.) — decoding doesn't need the key." },
      { question: "Can I paste an access token from my app?", answer: "Yes, any standard three-part JWT works. Remember: only paste tokens you're allowed to see." },
      { question: "Does it work on mobile?", answer: "Yes, fully responsive." },
      { question: "What's the difference between a JWT and a session?", answer: "A JWT is stateless — the server validates the signature without storing session data. This decoder helps you inspect what's inside a token." },
    ],
  },

  "sql-formatter": {
    meta: { readTime: "4 min read", updated: "August 2026", author: "Vizo Tool" },
    highlights: ["Beautify & minify", "Syntax highlighting", "Upload SQL files", "12+ SQL dialects"],
    intro: {
      heading: "SQL Formatter — Beautify & Minify SQL Queries",
      paragraphs: [
        "The SQL Formatter turns messy queries into clean, readable SQL with proper indentation, or minifies them down for storage. Syntax highlighting makes keywords, strings, and numbers easy to scan, and it supports 12+ SQL dialects including MySQL, PostgreSQL, and SQL Server.",
        "Paste a query, upload a .sql file, or type directly — the formatted result updates instantly. Everything runs in your browser, so proprietary schema queries stay private.",
      ],
    },
    benefits: [
      { title: "Instant Beautify", description: "Clean indentation and line breaks make complex queries readable." },
      { title: "Minify Mode", description: "Collapse queries to compact one-liners for storage or logs." },
      { title: "12+ SQL Dialects", description: "MySQL, PostgreSQL, SQL Server, SQLite, BigQuery, and more." },
      { title: "100% Private", description: "Formatting happens locally — your queries never leave your device." },
    ],
    features: [
      { title: "Beautify", description: "Indent keywords, clauses, and subqueries with correct line breaks." },
      { title: "Minify", description: "Produce compact single-line SQL for saving space." },
      { title: "Syntax Highlighting", description: "Color-coded keywords, strings, numbers, and comments." },
      { title: "Upload & Download", description: "Load a .sql file and download the formatted result." },
      { title: "Dialect Selector", description: "Choose your database flavor for the most accurate formatting." },
      { title: "Copy Anywhere", description: "Copy the formatted output with one click." },
    ],
    howTo: {
      heading: "How to Format SQL",
      description: "Clean up any query in three steps.",
      steps: [
        { name: "Paste or upload SQL", text: "Paste your query or load a .sql file into the editor." },
        { name: "Pick a dialect", text: "Select your database (MySQL, PostgreSQL, etc.) for the best formatting." },
        { name: "Format & copy", text: "Choose Beautify or Minify, then copy or download the result." },
      ],
    },
    faqs: [
      { question: "What is a SQL formatter?", answer: "It reformats SQL code with proper indentation and line breaks to make it readable, or compacts it to save space." },
      { question: "Is the SQL formatter free?", answer: "Yes, completely free with no sign-ups." },
      { question: "Are my queries uploaded?", answer: "No — all formatting happens locally in your browser." },
      { question: "Which SQL dialects are supported?", answer: "MySQL, PostgreSQL, SQL Server, SQLite, BigQuery, Snowflake, MariaDB, Oracle, and more — over 12 dialects." },
      { question: "What does Minify do?", answer: "It removes unnecessary whitespace and line breaks to produce a compact single-line query." },
      { question: "Can I format a .sql file?", answer: "Yes, upload any .sql file and the tool reads and formats it automatically." },
      { question: "Does it support syntax highlighting?", answer: "Yes, keywords, strings, numbers, and comments are color-coded for readability." },
      { question: "Can I download the formatted result?", answer: "Yes, download the output as a .sql file." },
      { question: "Will it handle CTEs and subqueries?", answer: "Yes — WITH clauses, CTEs, subqueries, and joins are indented correctly." },
      { question: "Does it work on mobile?", answer: "Yes, fully responsive." },
      { question: "Can I copy just the formatted output?", answer: "Yes, one click copies the formatted SQL." },
      { question: "Why should I format my SQL?", answer: "Readable SQL is easier to debug, review, and maintain — and formatted queries are far less error-prone when edited." },
    ],
  },
};
