import {
  BadgePercent,
  BarChart3,
  Binary,
  Bot,
  Box,
  Braces,
  CandlestickChart,
  ChartLine,
  Coins,
  Code2,
  Crop,
  Database,
  FileImage,
  FileJson,
  FileText,
  Fingerprint,
  FlipHorizontal2,
  Gauge,
  Hash,
  Heading,
  Home,
  IdCard,
  KeyRound,
  Landmark,
  Layers,
  Link2,
  Network,
  Palette,
  PenLine,
  Percent,
  QrCode,
  Receipt,
  Repeat,
  ScanSearch,
  Search,
  Share2,
  ShieldCheck,
  SquareTerminal,
  Stamp,
  Sun,
  Tags,
  Target,
  TextCursorInput,
  TrendingDown,
  TrendingUp,
  Wallet,
  Wand2,
  type LucideIcon,
} from "lucide-react";

/**
 * Per-tool icon keyed by registry slug (see lib/tools.ts). Client-only file —
 * do NOT import from server files (sitemap.ts etc.) since lucide pulls in
 * client code.
 */
export const TOOL_ICONS: Record<string, LucideIcon> = {
  compress: Gauge,
  resize: Crop,
  flip: FlipHorizontal2,
  convert: Repeat,
  "watermark-image": Stamp,
  "remove-background": Wand2,
  "passport-photo-maker": IdCard,
  "image-to-pdf": FileText,
  "pdf-to-image": FileImage,
  "signature-resizer": PenLine,
  "social-media-resizer": Share2,
  "json-formatter": Braces,
  "json-validator": ShieldCheck,
  "base64-encoder": Binary,
  "base64-decoder": Binary,
  "password-generator": KeyRound,
  "uuid-generator": Hash,
  "qr-code-generator": QrCode,
  "css-gradient-generator": Palette,
  "css-box-shadow-generator": Box,
  "jwt-decoder": Fingerprint,
  "sql-formatter": Database,
  "meta-tag-generator": Tags,
  "schema-markup-generator": FileJson,
  "open-graph-generator": Share2,
  "robots-txt-generator": Bot,
  "sitemap-generator": Network,
  "utm-builder": Link2,
  "serp-preview": Search,
  "slug-generator": TextCursorInput,
  "meta-tag-analyzer": ScanSearch,
  "heading-checker": Heading,
  "website-traffic-checker": BarChart3,
  "html-css-js-playground": Code2,
  "sql-playground": SquareTerminal,
  // Finance Tools
  "sip-calculator": TrendingUp,
  "compound-interest-calculator": Layers,
  "emi-calculator": Home,
  "gst-calculator": Percent,
  "fd-calculator": Landmark,
  "cagr-calculator": ChartLine,
  "roi-calculator": Target,
  "income-tax-calculator": Receipt,
  "retirement-calculator": Sun,
  "discount-calculator": BadgePercent,
  "profit-margin-calculator": Coins,
  "stock-average-calculator": CandlestickChart,
  "salary-calculator": Wallet,
  "inflation-calculator": TrendingDown,
};

/** Fallback icon for slugs not in the map. */
export const FALLBACK_TOOL_ICON: LucideIcon = Repeat;

export function getToolIcon(slug: string): LucideIcon {
  return TOOL_ICONS[slug] ?? FALLBACK_TOOL_ICON;
}
